/* How Many Beers - Drinking Map test feature */
(function () {
  const MAP_SUPABASE_URL = 'https://tmwmsmkivxyenulifmdk.supabase.co';
  const MAP_SUPABASE_KEY = 'sb_publishable_Up-QZhkzCGzgO59fyF-zag_K7PSpYmU';
  const mapSb = supabase.createClient(MAP_SUPABASE_URL, MAP_SUPABASE_KEY);
  const MAP_FUNCTION_URL = `${MAP_SUPABASE_URL}/functions/v1/find-nearby-venues`;
  let mapInstance = null, mapMarkers = [], selectedGroupCode = null, activeSession = null, venueCandidates = [], originalAdjustDrink = null, originalSwitchPage = null;
  const el = id => document.getElementById(id);
  const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, c => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' }[c]));

  function addStyles() {
    if (el('drinking-map-styles')) return;
    const style = document.createElement('style'); style.id = 'drinking-map-styles';
    style.textContent = '#drinking-map-page .map-card{background:var(--bg-card);border:1px solid var(--border-color);border-radius:12px;padding:16px;margin-bottom:16px}#drinking-map-page .venue-candidate{width:100%;text-align:left;background:var(--bg-main);color:var(--text-main);border:1px solid var(--border-color);border-radius:9px;padding:11px;margin-top:8px;cursor:pointer}#drinking-map-page .venue-candidate:hover{border-color:var(--primary-color)}#drinking-map-page .venue-name{font-weight:800;display:block}#drinking-map-page .venue-meta{font-size:11px;color:var(--text-muted);display:block;margin-top:3px}#drinking-map-page #drinking-map-canvas{width:100%;height:360px;border-radius:10px;overflow:hidden;background:var(--bg-main)}#drinking-map-page .map-rank-row{display:flex;justify-content:space-between;gap:10px;align-items:center;padding:10px 0;border-bottom:1px solid var(--border-color)}#drinking-map-page .map-rank-row:last-child{border-bottom:none}#drinking-map-page .map-rank-main{min-width:0}#drinking-map-page .map-rank-name{font-weight:800;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}#drinking-map-page .map-rank-meta{color:var(--text-muted);font-size:11px;margin-top:2px}.leaflet-container{font:inherit}';
    document.head.appendChild(style);
  }
  function loadLeaflet() {
    if (window.L) return Promise.resolve(); if (window.__howManyLeafletPromise) return window.__howManyLeafletPromise;
    window.__howManyLeafletPromise = new Promise((resolve, reject) => { const css=document.createElement('link'); css.rel='stylesheet'; css.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css'; document.head.appendChild(css); const script=document.createElement('script'); script.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js'; script.onload=resolve; script.onerror=reject; document.head.appendChild(script); });
    return window.__howManyLeafletPromise;
  }
  function addMapPage() {
    if (el('drinking-map-page')) return;
    const page=document.createElement('div'); page.id='drinking-map-page'; page.className='hidden';
    page.innerHTML='<div class="map-card"><h3 style="margin:0 0 6px;color:var(--primary-color);">📍 Drinking Map</h3><p style="font-size:12px;color:var(--text-muted);margin:0 0 12px;">Log where you are drinking. Google Places suggests nearby pubs/bars; you confirm the venue.</p><label>MAP FOR</label><select id="drinking-map-group-select"></select><div id="active-drinking-location"></div><button id="set-drinking-location-btn" class="btn-submit" onclick="setDrinkingLocation()">Set My Drinking Location 📍</button><div id="venue-candidates"></div></div><div class="map-card"><div style="display:flex;justify-content:space-between;align-items:center;gap:8px;"><div><h3 style="margin:0;font-size:15px;color:var(--text-muted);">POPULAR DRINKING DESTINATIONS</h3><span style="font-size:10px;color:var(--text-muted);">Based on confirmed drink events</span></div><button class="btn-secondary" style="font-size:11px;" onclick="refreshDrinkingMap()">Refresh</button></div><div id="drinking-map-canvas" style="margin-top:12px;"></div></div><div class="map-card"><h3 style="margin:0 0 8px;font-size:15px;color:var(--text-muted);">MOST VISITED</h3><div id="drinking-map-ranking"></div></div>';
    el('app-screen').appendChild(page); const nav=document.querySelector('#app-screen nav');
    if(nav&&!el('nav-map')){const button=document.createElement('button');button.id='nav-map';button.onclick=()=>switchPage('map');button.textContent='Map';nav.insertBefore(button,el('nav-admin'));}
    el('drinking-map-group-select').addEventListener('change',async e=>{selectedGroupCode=e.target.value||null;await loadActiveSession();await refreshDrinkingMap();});
  }
  async function currentUser(){const {data}=await mapSb.auth.getSession();return data?.session?.user||null;}
  async function populateGroupSelect(){const user=await currentUser();if(!user)return;const {data}=await mapSb.from('group_members').select('group_code, groups(name)').eq('user_email',user.email);const select=el('drinking-map-group-select');if(!select)return;const groups=(data||[]).map(row=>({code:row.group_code,name:row.groups?.name||row.group_code}));if(!selectedGroupCode&&groups.length)selectedGroupCode=groups[0].code;select.innerHTML='<option value="">Personal / all logged events</option>'+groups.map(g=>`<option value="${escapeHtml(g.code)}">${escapeHtml(g.name)}</option>`).join('');select.value=selectedGroupCode||'';}
  async function loadActiveSession(){const user=await currentUser();if(!user)return;let query=mapSb.from('drinking_sessions').select('*').eq('user_email',user.email).is('ended_at',null).order('started_at',{ascending:false}).limit(1);query=selectedGroupCode?query.eq('group_code',selectedGroupCode):query.is('group_code',null);const {data}=await query.maybeSingle();activeSession=data||null;renderActiveLocation();}
  function renderActiveLocation(){const target=el('active-drinking-location');if(!target)return;target.innerHTML=activeSession?`<div style="background:var(--bg-main);border:1px solid var(--primary-color);border-radius:8px;padding:10px;font-size:12px;margin-top:10px;"><strong>📍 ${escapeHtml(activeSession.venue_name)}</strong><br><span style="color:var(--text-muted);">${escapeHtml(activeSession.venue_address||'')}</span><button class="btn-secondary" style="float:right;margin-top:-4px;" onclick="endDrinkingSession()">Change</button></div>`:'<div style="margin-top:10px;color:var(--text-muted);font-size:12px;">No active drinking location. Set one before logging drinks if you want them included on the map.</div>';}
  function distanceMetres(aLat,aLng,bLat,bLng){const R=6371000,p1=aLat*Math.PI/180,p2=bLat*Math.PI/180,dp=(bLat-aLat)*Math.PI/180,dl=(bLng-aLng)*Math.PI/180,h=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(h),Math.sqrt(1-h));}
  function getPosition(){return new Promise((resolve,reject)=>{if(!navigator.geolocation)return reject(new Error('Location is not available on this device.'));navigator.geolocation.getCurrentPosition(resolve,reject,{enableHighAccuracy:true,timeout:10000,maximumAge:60000});});}
  async function setDrinkingLocation(){const button=el('set-drinking-location-btn'),candidates=el('venue-candidates');button.disabled=true;button.textContent='Finding nearby pubs…';candidates.innerHTML='';try{const position=await getPosition();const response=await fetch(MAP_FUNCTION_URL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({latitude:position.coords.latitude,longitude:position.coords.longitude,radius:180})});const payload=await response.json();if(!response.ok)throw new Error(payload.error||'Could not find nearby venues');venueCandidates=(payload.places||[]).map(p=>({...p,distance:distanceMetres(position.coords.latitude,position.coords.longitude,p.latitude,p.longitude)}));candidates.innerHTML=venueCandidates.length?'<div style="font-size:12px;color:var(--text-muted);margin-top:12px;">Which venue are you at?</div>'+venueCandidates.slice(0,5).map((p,i)=>`<button class="venue-candidate" onclick="confirmDrinkingVenue(${i})"><span class="venue-name">${escapeHtml(p.name)}</span><span class="venue-meta">${Math.round(p.distance)}m away${p.address?' · '+escapeHtml(p.address):''}</span></button>`).join(''):'<div style="margin-top:10px;color:var(--text-muted);font-size:12px;">No nearby pubs/bars were returned. Try again outside or widen the search.</div>';}catch(error){candidates.innerHTML=`<div style="margin-top:10px;color:#fca5a5;font-size:12px;">${escapeHtml(error.message||'Could not determine your location.')}</div>`;}finally{button.disabled=false;button.textContent='Set My Drinking Location 📍';}}
  async function confirmDrinkingVenue(index){const place=venueCandidates[index],user=await currentUser();if(!place||!user)return;if(activeSession)await endDrinkingSession(true);const {data,error}=await mapSb.from('drinking_sessions').insert([{user_email:user.email,group_code:selectedGroupCode||null,google_place_id:place.id,venue_name:place.name,venue_address:place.address||null,latitude:place.latitude,longitude:place.longitude}]).select().single();if(error)return alert(error.message);activeSession=data;venueCandidates=[];el('venue-candidates').innerHTML='<div style="margin-top:10px;color:var(--text-muted);font-size:12px;">Venue confirmed. New drink logs will be attributed to this destination.</div>';renderActiveLocation();}
  async function endDrinkingSession(silent){if(!activeSession)return;await mapSb.from('drinking_sessions').update({ended_at:new Date().toISOString()}).eq('id',activeSession.id);activeSession=null;renderActiveLocation();if(!silent&&el('venue-candidates'))el('venue-candidates').innerHTML='<div style="margin-top:10px;color:var(--text-muted);font-size:12px;">Location cleared.</div>';}
  async function recordDrinkEvent(type,delta,logDate){if(!activeSession||!delta)return;const user=await currentUser();if(!user)return;await mapSb.from('drink_location_events').insert([{session_id:activeSession.id,user_email:user.email,group_code:activeSession.group_code,log_date:logDate,drink_type:type,delta}]);}
  async function refreshDrinkingMap(){const user=await currentUser();if(!user)return;await loadLeaflet();let query=mapSb.from('drink_location_events').select('*, drinking_sessions(*)');query=selectedGroupCode?query.eq('group_code',selectedGroupCode):query.is('group_code',null);const {data,error}=await query;if(error){el('drinking-map-ranking').innerHTML=`<div style="color:#fca5a5;font-size:12px;">${escapeHtml(error.message)}</div>`;return;}const totals={};(data||[]).forEach(event=>{const session=event.drinking_sessions;if(!session)return;const key=session.google_place_id;if(!totals[key])totals[key]={id:key,name:session.venue_name,address:session.venue_address,lat:session.latitude,lng:session.longitude,drinks:0,visits:new Set(),users:new Set()};totals[key].drinks+=Number(event.delta||0);totals[key].visits.add(session.id);totals[key].users.add(event.user_email);});const venues=Object.values(totals).filter(v=>v.drinks>0).sort((a,b)=>b.drinks-a.drinks);renderMap(venues);el('drinking-map-ranking').innerHTML=venues.length?venues.slice(0,10).map((v,i)=>`<div class="map-rank-row"><div class="map-rank-main"><div class="map-rank-name">${i+1}. ${escapeHtml(v.name)}</div><div class="map-rank-meta">${v.visits.size} visit${v.visits.size===1?'':'s'} · ${v.users.size} drinker${v.users.size===1?'':'s'}</div></div><strong>${v.drinks} 🍺</strong></div>`).join(''):'<div style="color:var(--text-muted);font-size:12px;">No location-linked drinks yet. Set a venue and log a drink to start the map.</div>';}
  function renderMap(venues){const container=el('drinking-map-canvas');if(!container||!window.L)return;if(!mapInstance){mapInstance=L.map(container,{zoomControl:true}).setView([51.5,-0.1],6);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'&copy; OpenStreetMap contributors'}).addTo(mapInstance);}mapMarkers.forEach(m=>m.remove());mapMarkers=[];if(!venues.length){mapInstance.setView([51.5,-0.1],6);return;}const bounds=[];venues.forEach(v=>{const radius=Math.max(8,Math.min(30,8+Math.sqrt(v.drinks)*3));const marker=L.circleMarker([v.lat,v.lng],{radius,weight:2,fillOpacity:.75});marker.bindPopup(`<strong>${escapeHtml(v.name)}</strong><br>${v.drinks} drinks · ${v.visits.size} visits`);marker.addTo(mapInstance);mapMarkers.push(marker);bounds.push([v.lat,v.lng]);});if(bounds.length===1)mapInstance.setView(bounds[0],15);else mapInstance.fitBounds(bounds,{padding:[20,20],maxZoom:14});setTimeout(()=>mapInstance.invalidateSize(),100);}
  function installHooks(){if(!originalAdjustDrink&&typeof window.adjustDrink==='function'){originalAdjustDrink=window.adjustDrink;window.adjustDrink=async function(type,delta){const countEl=document.getElementById(`cnt-${type}`),before=Number(countEl?.innerText||0);await originalAdjustDrink(type,delta);const after=Number(countEl?.innerText||0),logDate=document.getElementById('today-date-label')?.innerText||new Date().toISOString().slice(0,10);if(after===before+delta)await recordDrinkEvent(type,delta,logDate);};}if(!originalSwitchPage&&typeof window.switchPage==='function'){originalSwitchPage=window.switchPage;window.switchPage=function(page){if(page==='map'){['page-account','page-tracker','page-stats','page-admin'].forEach(id=>el(id)?.classList.add('hidden'));el('drinking-map-page')?.classList.remove('hidden');document.querySelectorAll('#app-screen nav button').forEach(b=>b.classList.remove('active'));el('nav-map')?.classList.add('active');populateGroupSelect().then(loadActiveSession).then(refreshDrinkingMap);return;}el('drinking-map-page')?.classList.add('hidden');originalSwitchPage(page);};}}
  async function init(){addStyles();addMapPage();installHooks();mapSb.auth.onAuthStateChange(async(_event,session)=>{if(session?.user){await populateGroupSelect();await loadActiveSession();}else activeSession=null;});const user=await currentUser();if(user){await populateGroupSelect();await loadActiveSession();}}
  window.setDrinkingLocation=setDrinkingLocation;window.confirmDrinkingVenue=confirmDrinkingVenue;window.endDrinkingSession=endDrinkingSession;window.refreshDrinkingMap=refreshDrinkingMap;init().catch(err=>console.error('Drinking Map init failed',err));
})();
