-- Drinking tracker persistence and venue event storage.
-- Safe to run against an existing project: existing columns/tables are preserved.

create table if not exists public.drinking_sessions (
  id bigint generated by default as identity primary key,
  user_email text not null,
  group_code text,
  google_place_id text,
  venue_name text not null,
  venue_address text,
  latitude double precision,
  longitude double precision,
  created_at timestamptz not null default now(),
  started_at timestamptz not null default now(),
  ended_at timestamptz
);

alter table public.drinking_sessions add column if not exists user_email text;
alter table public.drinking_sessions add column if not exists group_code text;
alter table public.drinking_sessions add column if not exists google_place_id text;
alter table public.drinking_sessions add column if not exists venue_name text;
alter table public.drinking_sessions add column if not exists venue_address text;
alter table public.drinking_sessions add column if not exists latitude double precision;
alter table public.drinking_sessions add column if not exists longitude double precision;
alter table public.drinking_sessions add column if not exists created_at timestamptz not null default now();
alter table public.drinking_sessions add column if not exists started_at timestamptz not null default now();
alter table public.drinking_sessions add column if not exists ended_at timestamptz;

create index if not exists drinking_sessions_user_email_idx on public.drinking_sessions(user_email);
create index if not exists drinking_sessions_active_idx on public.drinking_sessions(user_email, ended_at);

create table if not exists public.drink_location_events (
  id bigint generated by default as identity primary key,
  session_id bigint not null references public.drinking_sessions(id) on delete cascade,
  user_email text not null,
  group_code text,
  log_date date not null,
  drink_type text not null,
  delta integer not null,
  created_at timestamptz not null default now()
);

create index if not exists drink_location_events_session_idx on public.drink_location_events(session_id);
create index if not exists drink_location_events_user_date_idx on public.drink_location_events(user_email, log_date);

alter table public.drinking_sessions enable row level security;
alter table public.drink_location_events enable row level security;

drop policy if exists "drinking_sessions_select_authenticated" on public.drinking_sessions;
create policy "drinking_sessions_select_authenticated"
  on public.drinking_sessions for select
  to authenticated
  using (true);

drop policy if exists "drinking_sessions_insert_own" on public.drinking_sessions;
create policy "drinking_sessions_insert_own"
  on public.drinking_sessions for insert
  to authenticated
  with check (user_email = (auth.jwt() ->> 'email'));

-- This was the missing piece behind checkout appearing to succeed while the
-- open session remained after refresh.
drop policy if exists "drinking_sessions_update_own" on public.drinking_sessions;
create policy "drinking_sessions_update_own"
  on public.drinking_sessions for update
  to authenticated
  using (user_email = (auth.jwt() ->> 'email'))
  with check (user_email = (auth.jwt() ->> 'email'));

drop policy if exists "drink_location_events_select_authenticated" on public.drink_location_events;
create policy "drink_location_events_select_authenticated"
  on public.drink_location_events for select
  to authenticated
  using (true);

drop policy if exists "drink_location_events_insert_own" on public.drink_location_events;
create policy "drink_location_events_insert_own"
  on public.drink_location_events for insert
  to authenticated
  with check (user_email = (auth.jwt() ->> 'email'));
